### PR TITLE
[feature-request] add return value undefined

### PR DESCRIPTION
**Pull request by Kanti**
see #10

### CODE REVIEW

**Comment by Kanti** [comment]
I haven't tested the parse functionality

**Comment by Kanti** [comment]
@MaiaVictor now it should be functional and ready to merge.

**Comment by VictorTaelin** [comment]
Hey! Very cool. But what do you mean with "should"? All tests (i.e., examples) ok?

**Comment by Kanti** [comment]
All Exempels worked.

**Comment by VictorTaelin** [comment]
I see, thank you! 

... now that I actually think about it, returning "undefined" looks like a bad idea, no? After all it wasn't part of the specs before. What do you think?

**Pull request merged**
